### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RoelvdBurght** [RoelvdBurght/complex-systems#1]
Model:

- [x] Straten

- [x]  Restrictions
  - [ ] Street density check
  - [ ] Industry check
  - [ ] Housing check
  - [ ]  Storage check

**Comment by RoelvdBurght** [comment]
Nog doen:
- [ ] Elke activity eigen decay function/parameter
- [ ] Metrics opstellen (beetje vaag)
- [ ] Verschillende initialisaties
- [ ] Grafieken van gemiddelde ratio housing/industry etc voor verschillende parameter waardes (phase transition zoeken)
- [ ] Gui visualisatie

Misschien interessant:
- [ ] Elke activity eigen distance parameter
